cloud:
  aws:
    credentials:
      access-key: Your-Access-Key-Enter-Here
      secret-key: Your-Security-Key-Enter-Here
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: downloadexcelfile


server:
  port: 9090

