cloud:
  aws:
    credentials:
      access-key: AKIAZSNXT2UBWYQ2SZCN
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: downloadexcelfile


server:
  port: 9090

